import { LegalPage, Section, SubSection } from "@/components/layout/legal-page";

export const metadata = {
  title: "Terms of Use — Corki",
  description: "Terms governing your use of the Corki app.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use" updated="17 March 2026">
      <p style={{ color: "#A39B95" }}>
        These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of the <strong style={{ color: "#F9F6F4" }}>Corki</strong> mobile application (&ldquo;App&rdquo;). By using the App you agree to be bound by these Terms.
      </p>

      <Section heading="1. Age Requirement">
        <p>
          You must be at least <strong style={{ color: "#F9F6F4" }}>18 years old</strong> (or the legal drinking age in your jurisdiction, whichever is higher) to use Corki. We reserve the right to terminate access if we believe this requirement is not met.
        </p>
      </Section>

      <Section heading="2. Description of Service">
        <p>
          Corki is an AI-powered wine information assistant. The App offers wine recommendations, label analysis, cellar management tools, and wine education. All content is generated by artificial intelligence and is intended for informational and personal enjoyment purposes only.
        </p>
      </Section>

      <Section heading="3. Alcohol Disclaimer">
        <p>
          Corki provides wine information for educational purposes only and does not substitute for professional medical or nutritional advice. You should consult health professionals about dietary concerns before consuming alcohol. We encourage responsible consumption and discourage excessive drinking.
        </p>
      </Section>

      <Section heading="4. Allergen and Health Disclaimer">
        <p>
          Wine may contain allergens such as sulphites and animal-derived fining agents. Information provided by Corki about wine composition, ingredients, or allergens is generated by AI and may not be complete, accurate, or current. You must verify allergen information through product labels and qualified professionals.
        </p>
      </Section>

      <Section heading="5. Free Tier and Corki Pro">
        <SubSection heading="5.1 Free Tier">
          <p>
            New users receive 10 free messages without registration. Free-tier access may be limited or discontinued at any time.
          </p>
        </SubSection>

        <SubSection heading="5.2 Corki Pro Subscription">
          <p>
            Corki Pro is an auto-renewing subscription that unlocks unlimited conversations, label scans, cellar management, full chat history, and premium themes. Pricing is AUD $5.99/month or AUD $49.99/year.
          </p>
        </SubSection>

        <SubSection heading="5.3 Billing and Renewal">
          <p>
            Charges are applied to your Apple ID account. Subscriptions renew automatically unless cancelled at least 24 hours before the end of the current billing period.
          </p>
        </SubSection>

        <SubSection heading="5.4 Cancellation">
          <p>
            You may cancel your subscription through your Apple ID settings. Cancellation takes effect at the end of the current billing period. No prorated refunds are issued.
          </p>
        </SubSection>

        <SubSection heading="5.5 Free Trials">
          <p>
            Any unused portion of a free trial is forfeited upon subscription purchase.
          </p>
        </SubSection>

        <SubSection heading="5.6 Restore Purchases">
          <p>
            You can restore previous purchases made on the same Apple ID from within the App.
          </p>
        </SubSection>
      </Section>

      <Section heading="6. Intellectual Property">
        <p>
          We own or license all App content, design, trademarks, and software. You may not copy, reproduce, modify, or distribute any part of the App without our prior written permission. AI-generated responses are provided for personal use only.
        </p>
      </Section>

      <Section heading="7. User Conduct">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use the App unlawfully or in violation of applicable laws</li>
          <li>Reverse engineer, decompile, or extract source code</li>
          <li>Use automated tools to scrape or abuse the service</li>
          <li>Submit defamatory or harmful content that infringes third-party rights</li>
          <li>Circumvent usage limits or access controls</li>
        </ul>
      </Section>

      <Section heading="8. Disclaimer of Warranties">
        <p>
          The App and all content are provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, whether express or implied. We do not warrant uninterrupted service, error-free operation, or the accuracy of AI-generated responses.
        </p>
      </Section>

      <Section heading="9. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, our total liability shall not exceed the amount you paid us in the preceding 12 months, or AUD $10.00 if you are an unpaid user. Nothing in these Terms excludes or limits rights under the Australian Consumer Law that cannot be excluded.
        </p>
      </Section>

      <Section heading="10. Third-Party Services">
        <p>
          The App relies on OpenAI for AI processing and Apple for payment processing. We bear no responsibility for their availability, accuracy, or conduct.
        </p>
      </Section>

      <Section heading="11. Privacy">
        <p>
          How we handle your personal information is described in our{" "}
          <a href="/privacy" style={{ color: "#D4944A" }}>Privacy Policy</a>, which is incorporated into these Terms by reference.
        </p>
      </Section>

      <Section heading="12. Governing Law">
        <p>
          These Terms are governed by the laws of New South Wales, Australia. If you are a consumer in the European Union, you may also rely on the mandatory consumer-protection laws of your country of residence.
        </p>
      </Section>

      <Section heading="13. Changes to These Terms">
        <p>
          We may update these Terms from time to time. We will notify you of material changes within the App. Continued use of the App after changes constitutes acceptance.
        </p>
      </Section>

      <Section heading="14. Contact">
        <p>
          Questions about these Terms:{" "}
          <a href="mailto:legal@corki.app" style={{ color: "#D4944A" }}>legal@corki.app</a>
        </p>
      </Section>
    </LegalPage>
  );
}
