import { LegalPage, Section } from "@/components/layout/legal-page";

export const metadata = {
  title: "Age Restriction — Corki",
  description: "Corki is intended for users of legal drinking age.",
};

export default function AgeRestrictionPage() {
  return (
    <LegalPage title="Age Restriction" updated="17 March 2026">
      <Section heading="You must be of legal drinking age">
        <p>
          Corki is an AI-powered wine assistant. Because the App discusses alcoholic beverages, you must be at least{" "}
          <strong style={{ color: "#F9F6F4" }}>18 years old</strong> &mdash; or the legal drinking age in your jurisdiction, whichever is higher &mdash; to use Corki.
        </p>
      </Section>

      <Section heading="Age confirmation">
        <p>
          When you first open the App, you are asked to confirm that you meet the minimum age requirement. By continuing to use Corki, you represent and warrant that you are of legal drinking age in your jurisdiction.
        </p>
      </Section>

      <Section heading="No alcohol sales">
        <p>
          Corki does not sell, supply, or facilitate the purchase of alcohol. The App provides wine information, education, and cellar management tools for personal use only. Any wine details, recommendations, or tasting notes are generated by AI for informational purposes.
        </p>
      </Section>

      <Section heading="Parental responsibility">
        <p>
          If you are a parent or guardian, please ensure that minors in your care do not access the App. If you believe someone under the legal drinking age is using Corki, please contact us and we will take appropriate action, including terminating their access and deleting any associated data.
        </p>
      </Section>

      <Section heading="Drink responsibly">
        <p>
          We encourage all users to consume alcohol responsibly. If you or someone you know needs support, please reach out to a local health professional or support service.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions about this policy:{" "}
          <a href="mailto:legal@corki.app" style={{ color: "#D4944A" }}>legal@corki.app</a>
        </p>
      </Section>
    </LegalPage>
  );
}
